In [1]:
!pip install sqlalchemy==1.3.9
!pip install ibm_db_sa

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
     |████████████████████████████████| 6.0 MB 26.9 MB/s eta 0:00:01
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp37-cp37m-linux_x86_64.whl size=1207765 sha256=927c49fdf350f331a04b4b029619624bb8951a2abbc60b99ca5be8d668a950c7
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/03/71/13/010faf12246f72dc76b4150e6e599d13a85b4435e06fb9e51f
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.17
    Uninstalling SQLAlchemy-1.3.17:
      Successfully uninstalled SQLAlchemy-1.3.17
Successfully installed sqlalchemy-1.3.9
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: ibm_db_sa in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (0.3.5)
Requirement already satisfied: sqlalchemy>=0.7.3 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ibm_db_sa) (1.3.9)
Requirement already satisfied: ibm-db>=2.0.0 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ibm_db_sa) (3.0.2)

In [2]:
pip install ipython-sql

/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting ipython-sql
  Downloading ipython_sql-0.4.0-py3-none-any.whl (19 kB)
Requirement already satisfied: six in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython-sql) (1.15.0)
Requirement already satisfied: ipython>=1.0 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython-sql) (7.15.0)
Collecting sqlparse
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 2.3 MB/s  eta 0:00:01
Collecting prettytable<1
  Downloading prettytable-0.7.2.tar.bz2 (21 kB)
Requirement already satisfied: sqlalchemy>=0.6.7 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython-sql) (1.3.9)
Requirement already satisfied: ipython-genutils>=0.1.0 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (3.0.5)
Requirement already satisfied: traitlets>=4.2 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.3.3)
Requirement already satisfied: jedi>=0.10 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.17.1)
Requirement already satisfied: backcall in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.2.0)
Requirement already satisfied: pygments in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (2.6.1)
Requirement already satisfied: pickleshare in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
Requirement already satisfied: decorator in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (47.3.1.post20200622)
Requirement already satisfied: pexpect; sys_platform != "win32" in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.8.0)
Requirement already satisfied: wcwidth in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.2.4)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.7.0)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/envs/Python-3.7-main/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=1.0->ipython-sql) (0.6.0)
Building wheels for collected packages: prettytable
  Building wheel for prettytable (setup.py) ... done
  Created wheel for prettytable: filename=prettytable-0.7.2-py3-none-any.whl size=13698 sha256=3288ae8d08d07ea8cb88320473c8d82f9fc99b5b98033f38daee60e62e5d11c3
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/8c/76/0b/eb9eb3da7e2335e3577e3f96a0ae9f74f206e26457bd1a2bc8
Successfully built prettytable
Installing collected packages: sqlparse, prettytable, ipython-sql
Successfully installed ipython-sql-0.4.0 prettytable-0.7.2 sqlparse-0.4.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
%load_ext sql

In [5]:
%sql ibm_db_sa://jdx89817:1xn92bwx%408zf7vv3@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB

## PROBLEM 1
### Find the total number of crimes recorded in the CRIME table.

In [6]:
%sql SELECT COUNT(*) AS TOTAL_CRIMES FROM CHICAGO_CRIME_DATA;

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

[(Decimal('533'),)]

## PROBLEM 2
### List community areas with per capita income less than 11000.

In [7]:
%sql SELECT COMMUNITY_AREA_NAME, PER_CAPITA_INCOME FROM CHICAGO_CENSUS_DATA WHERE PER_CAPITA_INCOME < 11000;

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

[('West Garfield Park', 10934),
 ('South Lawndale', 10402),
 ('Fuller Park', 10432),
 ('Riverdale', 8201)]

## PROBLEM 3
### List all case numbers for crimes involving minors?

In [8]:
%sql SELECT CASE_NUMBER FROM CHICAGO_CRIME_DATA WHERE PRIMARY_TYPE = 'OFFENSE INVOLVING CHILDREN';

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

[('HN567387',), ('HR391350',), ('HM768251',), ('HT394616',)]

## PROBLEM 4
### List all kidnapping crimes involving a child?

In [9]:
%sql SELECT PRIMARY_TYPE,CASE_NUMBER FROM CHICAGO_CRIME_DATA WHERE PRIMARY_TYPE = 'KIDNAPPING' AND DESCRIPTION LIKE '%CHILD%';

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

[('KIDNAPPING', 'HN144152')]

## PROBLEM 5
### What kind of crimes were recorded at schools?

In [10]:
%sql SELECT NAME_OF_SCHOOL, PRIMARY_TYPE \
FROM CHICAGO_CRIME_DATA CD, CHICAGO_PUBLIC_SCHOOLS PB \
WHERE CD.COMMUNITY_AREA_NUMBER = PB.COMMUNITY_AREA_NUMBER LIMIT 5;

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

[('Josephine C Locke Elementary School', 'CRIMINAL DAMAGE'),
 ('Josephine C Locke Elementary School', 'OTHER OFFENSE'),
 ('Abraham Lincoln Elementary School', 'THEFT'),
 ('Abraham Lincoln Elementary School', 'LIQUOR LAW VIOLATION'),
 ('Abraham Lincoln Elementary School', 'BURGLARY')]

## PROBLEM 6
### List the average safety score for all types of schools.

In [11]:
%sql SELECT AVG(SAFETY_SCORE) AS AVE_SAFETY_SCORE, \"ELEMENTARY, MIDDLE or HIGHSCHOOL\" \
FROM CHICAGO_PUBLIC_SCHOOLS \
GROUP BY \'ELEMENTARY, MIDDLE or HIGHSCHOOL\';

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: Exception('SQLNumResultCols failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0007N  The statement was not processed because a character that is not supported in SQL statements was included in the SQL statement.  Invalid character: "\\".  Text preceding the invalid character: "AS AVE_SAFETY_SCORE,".  SQLSTATE=42601 SQLCODE=-7')
[SQL: SELECT AVG(SAFETY_SCORE) AS AVE_SAFETY_SCORE, \"ELEMENTARY, MIDDLE or HIGHSCHOOL\" FROM CHICAGO_PUBLIC_SCHOOLS GROUP BY \'ELEMENTARY, MIDDLE or HIGHSCHOOL\';]
(Background on this error at: http://sqlalche.me/e/f405)

## PROBLEM 7
### List 5 community areas with highest % of households below poverty line.

In [12]:
%sql SELECT COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY \
FROM CHICAGO_CENSUS_DATA \
ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC NULLS LAST LIMIT 5;

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

[('Riverdale', Decimal('56.5')),
 ('Fuller Park', Decimal('51.2')),
 ('Englewood', Decimal('46.6')),
 ('North Lawndale', Decimal('43.1')),
 ('East Garfield Park', Decimal('42.4'))]

## PROBLEM 8
### Which community area(number) is most crime prone?

In [13]:
%sql SELECT COMMUNITY_AREA_NUMBER, COUNT(*) AS NUM_CRIME \
FROM CHICAGO_CRIME_DATA \
GROUP BY COMMUNITY_AREA_NUMBER ORDER BY NUM_CRIME DESC LIMIT 1;

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

[(25, Decimal('43'))]

## PROBLEM 9
### Use a sub-query to find the name of the community area with highest hardship index.

In [14]:
%sql SELECT COMMUNITY_AREA_NAME \
FROM CHICAGO_CENSUS_DATA \
WHERE HARDSHIP_INDEX = (SELECT MAX(HARDSHIP_INDEX) FROM CHICAGO_CENSUS_DATA);

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

[('Riverdale',)]

## PROBLEM 10
### Use a sub-query to determine the Community Area Name with most number of crimes?

In [15]:
%sql CREATE VIEW total_crime AS SELECT COMMUNITY_AREA_NUMBER, COUNT(*) AS number_of_crime FROM CHICAGO_CENSUS_DATA GROUP BY COMMUNITY_AREA_NUMBER;

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
(ibm_db_dbi.ProgrammingError) ibm_db_dbi::ProgrammingError: Exception('Statement Execute Failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0601N  The name of the object to be created is identical to the existing name "JDX89817.TOTAL_CRIME" of type "VIEW".  SQLSTATE=42710 SQLCODE=-601')
[SQL: CREATE VIEW total_crime AS SELECT COMMUNITY_AREA_NUMBER, COUNT(*) AS number_of_crime FROM CHICAGO_CENSUS_DATA GROUP BY COMMUNITY_AREA_NUMBER;]
(Background on this error at: http://sqlalche.me/e/f405)

In [16]:
%sql SELECT COMMUNITY_AREA_NAME FROM CHICAGO_PUBLIC_SCHOOLS PB WHERE PB.COMMUNITY_AREA_NUMBER = (SELECT COMMUNITY_AREA_NUMBER FROM TOTAL_CRIME WHERE NUMBER_OF_CRIME = (SELECT MAX(NUMBER_OF_CRIME) FROM TOTAL_CRIME));

 * ibm_db_sa://jdx89817:***@dashdb-txn-sbox-yp-dal09-12.services.dal.bluemix.net:50000/BLUDB
Done.

DBAPIError: (ibm_db_dbi.Error) ibm_db_dbi::Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0811N  The result of a scalar fullselect, SELECT INTO statement, or VALUES INTO statement is more than one row.  SQLSTATE=21000 SQLCODE=-811
(Background on this error at: http://sqlalche.me/e/dbapi)